# Konfigurasi untuk Bitbucket Pipelines

# Set image Docker yang digunakan untuk menjalankan pipeline
image: node:14.17.3

# Definisikan skrip untuk menjalankan tes
pipelines:
  branches:
    master:
      - step:
          name: Install dependencies
          script:
            - npm install
            - npm install bcrypt
            - chmod +x /opt/atlassian/pipelines/agent/build
          artifacts:
            - node_modules/**
      - step:
          name: Run tests
          script:
            - npm test
