# Konfigurasi untuk Bitbucket Pipelines

# Set image Docker yang digunakan untuk menjalankan pipeline
image: node:14.17.3-alpine

# Definisikan skrip untuk menjalankan tes
pipelines:
  branches:
    main:
      - step:
          name: Install dependencies
          script:
            - npm install
            - npm install bcrypt
            - chmod +x /opt/atlassian/pipelines/agent/build
          artifacts:
            - node_modules/**
      - step:
          name: Run tests
          script:
            - npm test
      - step:
          name: Build and Push Docker Image
          image: docker:latest
          services:
            - docker
          script:
            - source .env
            - docker build --no-cache -t firsabila/express-blanja-task .
            - docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker push firsabila/express-blanja-task
