const express = require("express")
const routing = express.Router()
const product = require("./routes/product")
const category = require("./routes/category")
const bag = require("./routes/bag")
const customer = require("./routes/customer")
const seller = require("./routes/seller")
const auth = require("./routes/auth")
const cs = require("./routes/authcs")
const { cloudConfig } = require("./configs/cloudinary")

routing.use("*", cloudConfig)
routing.use("api/product", product)
routing.use("api/category", category)
routing.use("api/bag", bag)
routing.use("api/customer", customer)
routing.use("api/seller", seller)
routing.use("api/auth", auth)
routing.use("api/authcs", cs)

module.exports = routing
